### ISSUE TITLE
Будет NPE, если пользователя с таким id нет. Либо выкидывайте свой Exception, либо работайте так, чтобы NPE не было.

### ISSUE THREAD

**Issue by coursar** [garail911/layers#5]
https://github.com/garail911/layers/blob/20cb6f99c199a40e8b98f8e566e649cf3a326cd3/src/main/java/tech/itpark/repository/UserRepositoryInMemoryImpl.java#L38-L39

**Comment by garail911** [comment]
Я в сервисе как раз выкидываю:
UserEntity entity = repository
            .findByLogin(model.getLogin())
            .orElseThrow(() -> new UsernameNotExistsException(model.getLogin()));
